boostcampwm-2022/Web10-MonumentGallery

client/.eslintrc.json, client/.prettierrc.json, client/package-lock.json, client/package.json, client/src/App.tsx
Co-authored-by: Seyeon Ko <koseyeon97@gmail.com>
Co-authored-by: lybell <lybell-art@users.noreply.github.com>
=> chore: prettier 적용

server/.gitignore, server/index.js, server/model/testSchema.js, server/package-lock.json, server/package.json
- 연결 테스트 api를 작성했습니다.
- mongodb 주소 등이 있는 env 파일은 임시로 private 슬랙에 공유됩니다.(추후 깃허브 서브모듈로 관리할 예정이라고 함)
=> feat: MongoDB 연결, 연결테스트 DB API 작성

windows-python-init.sh
mac도 셸스크립트가 존재하길래 windows 버전으로도 만들어 보았습니다.
=> chore: windows 파이썬 환경 구축 셸 스크립트 작성

client/src/CreatePage/CreatePage.tsx, client/src/CreatePage/api/fetchData.ts, client/src/components/SpaceCreater/index.tsx, server/router/testRouter.js, server/service/notionService.js
-modify: GET /test/getData가 쿼리스트링 내용을 반영하도록 수정
=> feat: 공간생성 모달에서 생성한 값이 반영된 api를 호출하도록 적용

python/main.py
nltk 라이브러리를 이용하여 영어 키워드도 추출해낼 수 있도록 구현하였습니다.
기존에는 konlpy의 형태소 분석기만을 사용하였기에 영어 키워드는 추출되지 않는 문제점이 있었습니다.
각 문장을 분석하기 전에, 미리 정규식을 돌려 한글 문장, 영어 문장으로 필터링해줍니다.
필터링된 한글,영어문장을 각각 kkma, nltk 분석기를 돌려 키워드를 추출합니다.
=> feat:영어 키워드도 추출할 수 있도록 구현

python/main.py, python/model.py, python/requirements.txt, server/router/testRouter.js, server/service/dataProcessService.js
전달받은 이미지 URL로부터 이미지 데이터를 받아온 후, 10 x 10 크기의 픽셀 배열로 만들어서 반환하는 API를 구현하였습니다.
사진의 시각화를 위해서, 사진 데이터로부터 RGB 픽셀 배열을 추출하는 로직이 필요했습니다.
- 이미지 전처리같은 로직은 python을 이용하는 것이 낫다고 생각하여, fastAPI 서버에 /preprocess/image API를 추가하였습니다.
- 기존의 키워드 추출 로직은 /preprocess/text 로 URL을 변경하였습니다.
- PIL 라이브러리를 이용해 구현하였습니다.
- 반환값 : 10 x 10 크기의 픽셀 배열
["0xda2028","0xda232b","0xdc2931","0xda1f27","0xda2028","0xda2028","0xda1f27","0xdc2931","0xdb232b","0xd92028","0xd91d25","0xde3a41","0xe87277","0xd8161f","0xd91c24","0xda1e26","0xd8151d","0xe8767a","0xde373f","0xd91d25","0xd91921","0xe76e73","0xee9a9e","0xdd333a","0xe0464d","0xdd2f36","0xe14c52","0xf2afb2","0xe24e55","0xd91d25","0xd91b23","0xf5c2c4","0xfefafa","0xf6c8ca","0xf8d4d5","0xef9da1","0xfcf0f0","0xffffff","0xf4babd","0xd91b23","0xd91a22","0xe87479","0xf1a9ac","0xf2adb0", …
=> feat:python PIL을 이용해 이미지 사이즈 조절 및 픽셀 배열 반환

client/src/GalleryPage/mapObjects/MemorialStone.tsx, python/main.py, python/model.py, python/requirements.txt, server/router/testRouter.js, server/service/dataProcessService.js
서브타이틀의 타입에 따라 폰트 사이즈, 스톤의 색이 변경되도록 하였습니다.
스톤 색깔은 정욱님이 추가하신 팔레트에서 Brown 3개를 골라서 썼습니다
=> feat: memorial stone type detail

client/src/GalleryPage/Gallery.tsx, client/src/GalleryPage/GalleryPage.tsx, client/src/GalleryPage/dummyData.ts, client/src/GalleryPage/mapObjects/AnimatedTitle.tsx, client/src/GalleryPage/mapObjects/GalleryPageIsland.tsx, client/src/GalleryPage/mapObjects/SubWordCloud.tsx, client/src/components/SpaceCreater/index.tsx, client/src/components/ThemeSelector/index.tsx
다음부터는 build 해서 돌아가는 지 확인하겠습니다 ㅠ.ㅠ
=> fix:merge-conflict로 인해 생긴  오류 해결

.github/workflows/Deploy.yml
=> chore: pr에만 demo 반응하도록 설정

proxy/nginx.conf
=> chore: nginx timeout 설정

client/src/CreatePage/CreatePage.tsx, client/src/GalleryPage/mapObjects/AnimatedTitle.tsx, client/src/GalleryPage/mapObjects/Bridge.tsx, client/src/GalleryPage/mapObjects/Pedestal.tsx, client/src/GalleryPage/mapObjects/Stone.tsx, client/src/GalleryPage/mapObjects/SubWordCloud.tsx, server/index.js, server/model/galleryModel.js, server/router/authRouter.js, server/router/galleryRouter.js, server/router/redirectRouter.js, server/service/dataSaveService.js
Auth 미들웨어의 사용 방식을 변경하였습니다.
현재 Auth 관련 미들웨어는 (redis에 부담이 될 수 있어서) 어떤 건 쓰고 어떤 건 안 쓰도록 구현하고 있습니다. 그런데 새로 미들웨어를 쓰는 api를 추가하려면 index.js에서도 수정해줘야 해서 부담스러운데다, 해당 api가 어떤 미들웨어를 쓰고 있는지 한눈에 파악하기 어렵습니다.
그래서 auth 미들웨어를 임포트해서 사용할 api가 auth 미들웨어를 사용하는 방식으로 변경하였습니다.
```javascript
router.get("/check", authMiddleware, (req, res) => {
const id = req.userid ?? null;
res.json({ logined: !!id, id });
});
```
- visible 속성을 이용하여 나타나고 사라지는 3D 컴포넌트에 대한 렌더링 최적화
- auth 미들웨어 방식 변경
- 비로그인 사용자가 주소창을 통해 페이지에 접근할 수 없었던 오류 해결
- #74
=> refactor: auth 미들웨어 방식 변경 (resolve #74)

server/schema/gallerySchema.js, server/service/imageProcessService.js
=> Fix 이미지 픽셀 타입 수정 String->Number

client/package-lock.json, client/package.json, client/src/CreatePage/CreatePage.tsx, client/src/components/ProgressBar/index.tsx, client/src/components/ProgressBar/style.scss, client/src/components/SpaceCreater/index.tsx, client/src/utils/URLCreator.ts, server/router/testRouter.js
SSE 방식으로 동작하는 Loading Bar를 구현하였습니다.
현재는 서버에게 요청을 보내면, 서버가 어디까지 작업을 진행하고 있는 중인지 알수 없었는데, 
SSE를 이용해서 중간 중간 단계마다 서버에서 클라이언트로 상태정보를 보내주면,
그에 맞게 현재 로딩 상태를 변경해주는 로직이 필요했습니다.
- 갤러리 만들기, 갤러리 동기화에 쓰였던 SpaceCreator 를 일부 수정했습니다.
- SuspenseButton 대신 LoadingBar를 쓰도록 했습니다.
- LoadingBar에는 
- eventSourceUrl (요청을 보낼 url 주소값),
- onLoad 함수 (작업이 완료되었을때 동작시킬 함수)가 전달됩니다.
- gsap을 추가하여 로딩 애니메이션이 부드럽게 동작하도록 했습니다.
=> Feat/loading bar-sse

client/src/GalleryPage/Gallery.tsx, client/src/GalleryPage/components/DomElements.tsx, client/src/GalleryPage/components/ViewRotateController.tsx
=> chore: 디버깅용 FPS 스탯 제거

readme.md
=> docs: readme 추가

server/model/galleryDummyData.js, server/service/galleryService.js, server/service/getNotionContentService.js
현재 어느 페이지를 불러오고 있는 지 추가로 표시함
기존 노션 데이터 불러오는 로직이 너무 길기 때문에, 노션 페이지를 불러오는 중입니다.. 에서 너무 오래 걸렸음
코드가 좀 더러워진 것 같아서 슬픕니다 ㅠㅠ
=> Refactor: loading

cron/.gitignore, server/index.js
=> Fix: 새로고침 시 쿠키 초기화 로직 추가

cron/.gitignore, cron/Dockerfile, cron/index.js, cron/model/galleryModel.js, cron/model/userModel.js, cron/package-lock.json, cron/package.json, cron/schema/gallerySchema.js, cron/schema/userSchema.js, server/router/testRouter.js
crontab 설정 완료
사용자에게 공유 강요 + 디비 공간 최적화를 위함
- 원래는 쉘로 node를 실행하고 crontab을 직접 써서 하고 싶었는데... nCloud가 이상한 건지 자꾸 메일 서버 관련 에러가 뜹니다.
- 그래서 node-cron 썼습니다. 쓰니까 금방 되네요.. 내다버린 3시간..
- node-cron으로 할거면 Docker로 구동시키는 게 나을 것 같아서 Dockerfile도 만들었습니다.
- 기존에는 shell로 실행해야 하는데 매번 Docker를 띄우기는 부담인 거 같아서 안 했는데, node-cron은 서버처럼 상시 가동이라 Docker로 띄우는게 더 나을 것 같더라구요
- 이 부분 배포 자동화는 고민중입니다. 딱히 수정이 더 없을 것 같아서
=> Feat: cron

client/src/MainPage/mapObjects/Monument.tsx, client/src/MainPage/mapObjects/Portal.tsx
- 포탈 크기가 안 바뀌는 문제를 수정했습니다.
- 모뉴먼트의 충돌 판정을 조금 늘렸습니다.
=> hotfix: 포탈 크기 수정

client/create.html, client/gallery.html, client/index.html, client/package-lock.json, client/package.json, client/src/MainPage/MainWorld.tsx, client/src/MainPage/components/SplashScreen/SplashScreen.tsx, client/src/components/ProgressBar/index.tsx, client/src/components/Spinner/index.tsx, client/src/components/Spinner/style.module.scss, client/src/components/buttons/SuspenseButton.tsx, server/index.js
font-awesome, gsap에 대한 의존성 제거
일부 버그 수정
(Before)
(After)
현재 로딩 성능을 약간 저해하는 요소 중 외부 요소를 사용하는 font-awesome, gsap의 사용이 존재하는데, 해당 부분을 덜어내면 번들링된 파일의 용량이 줄어들어서 초기 렌더링 성능을 향상시킬 수 있을 것이라 기대하였음.
현재 Font-Awesome cdn 라이브러리는 로딩 스피너만을 구현하기 위해 사용되었는데, 로딩 스피너는 CSS만으로 만들 수 있을 것이라고 판단되었고, 따라서 CSS 애니메이션으로 제작한 별도의 로딩 스피너 컴포넌트를 제작하여 Font-Awesome 외부 요소를 제거하였음.
현재 gsap은 로딩 프로그레시브 바 애니메이션을 구현하는 데 한정적으로 사용되고 있으나, 용량이 약 220KB로 많은 편임. 하지만 이 프로젝트에서는 애니메이션 라이브러리로 react-spring을 사용하고 있었기에, 해당 부분을 react-spring을 이용하여 구현하기로 하였음. 결론적으로는 **220.61KB에서 7.41KB**로 로딩 프로그레시브 바 애니메이션 라이브러리를 사용하는 용량이 획기적으로 줄어들었음.
- 스피너 컴포넌트 추가
- 프로그레스 바의 구현을 react-spring으로 변경
- SSR 요청 오류 시 요청을 다시 시도하지 않는 오류 해결(최대 5번까지 연속 요청)
=> refactor: 일부 의존성 제거

client/src/GalleryPage/mapObjects/GalleryPageIsland.tsx, server/service/galleryService.js, server/service/imageProcessService.js, server/utils/randoms.js
```
getRandomInt(0, 100) === 0 ? getMockData() : [];
```
그냥 간단하게 0~100까지 찍어보고 0이면 mockdata주는 식으로 했습니다.
```
{(imagePixel ? imagePixel.length > 0 : null) && <PictureFragments pixels={imagePixel} />}
```
imagePixel이 []로 들어오면 오류가 나서 임시로 저런 식으로 바꿨는데 다른 의견 주시면 적극 수용합니다
관련 issue #203
=> Fix: image mock data random

server/service/dataProcessService.js, server/service/galleryService.js, server/service/getNotionContentService.js
```
return await Promise.all(
pageContents[pageID].childPage
.filter((page) => Date.parse(page.lastEditedTime) >= limitTime)
.map(async (page) => {
return sumObject(
page,
page.type === "page"
? await getDataFromPage(notion, page.id)
: await getDataFromDatabase(notion, page.id),
);
}),
```
```
function sumChildPage(pageContent, limitTime) {
return pageContent
.reduce((acc, cur) => {
acc = [...acc, ...cur.childPage];
return acc;
}, [])
.filter((page) => Date.parse(page.lastEditedTime) >= limitTime);
}
function getMaxPage(pageContent, pageNum, limitTime) {
const childPage = sumChildPage(pageContent, limitTime);
return pageNum + childPage.length > 85 ? childPage.splice(0, 85 - pageNum) : childPage;
}
export async function getChildPage(notion, pageContent, pageNum, limitTime) {
const …
```
=> Refactor: intent

client/src/components/ThemeSelector/style.scss
우측 상단 테마 셀렉터의 스타일이 어긋나 보이는 버그 수정
Windows 환경 등에서 테마 셀렉터의 스타일이 어긋나 보이는 버그가 있었음.
=> design: 테마 셀렉터 스타일 어긋나는 버그 수정

client/src/MainPage/MainPage.tsx, client/src/MainPage/MainWorld.tsx
=> fix: MainWorld -> MainPage로 useError 위치 변경

server/service/galleryService.js
=> fix: gallerys->gallery

client/src/GalleryPage/Gallery.tsx, client/src/GalleryPage/GalleryPage.tsx, client/src/GalleryPage/components/CollisionPlayerBody.tsx, client/src/GalleryPage/mapObjects/Light.tsx, client/src/MainPage/MainCanvas.tsx, client/src/MainPage/components/MapDataFetcher.tsx, client/src/MainPage/components/Zoom.ts, client/src/MainPage/mapObjects/Environments/index.tsx, client/src/components/RoadSign/RoadSignHtml.tsx, client/src/components/RoadSign/style.scss, client/src/components/ThemeSelector/index.tsx
- 표지판 모달 iframe 제거, 새창에서 노션링크 여는 겻으로 변경
- 스펠링 잘못된 것, 재사용성 부족한 것들, 필요없는 훅 사용 제거
=> refactor: 여러가지 리팩토링

client/src/GalleryPage/components/CollisionPlayerBody.tsx
=> hotfix: _vector3 관련 오류 핫픽스

server/model/userModel.js
- 유저 생성 시 randIdx가 적용되지 않던 문제
단순하게 유저 생성시 랜덤 값을 넣어주는 걸로 해결했습니다
=> fix: 유저 생성시 randidx 적용
